# 使用官方 Python 镜像作为基础镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 将当前目录中的内容复制到容器的 /app 目录
COPY . .

# 安装 Python 依赖包
RUN pip install --no-cache-dir -r requirements.txt

# 暴露容器的 5000 端口
EXPOSE 5000

# 启动 Flask 应用
CMD ["python", "app.py"]

